<?php

//Defining individual user arrays
$superman = array('username' => 'superman', 'password' => 'kryptonite', 'email' => 'superman@ google.com');
$mario = array('username' => 'mario', 'password' => 'mushroom', 'email' => 'mario12@hawaii.edu');
$spiderman1 = array('username' => 'spiderman', 'password' => 'spider', 'email' => 'spiderman_web@mil.rr');
$itm352 = array('username' => 'itm352', 'password' => 'grader', 'email' => 'itm352@gmail.com');
$christie = array('username' => 'christie', 'password' => 'mattos', 'email' => 'csmattos@hawaii.edu');
$sheridan = array('username' => 'sheridan', 'password' => 'wu111', 'email' => 'wusherid@hawaii.edu');
//Defining array containing all users
$users = array($superman, $mario, $spiderman1, $itm352, $christie, $sheridan);

?>